using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;

namespace OnDaGO.MAUI.Models
{
    public class ReportItem
    {
        public string Id { get; set; }  // Auto-generated by the API
        public string UserId { get; set; }  // Add this field to store the user's ID
        public string Subject { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public bool IsImportant { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? DeletedAt { get; set; }
    }

}
